export const MOVIE_POSTERS: Record<string, string> = {
  "movie-1": "https://media.kitsu.app/anime/poster_images/487/original.jpg",
  "movie-2": "https://media.kitsu.app/anime/poster_images/1001/original.jpg",
  "movie-3": "https://media.kitsu.app/anime/poster_images/1002/original.jpg",
  "movie-4": "https://media.kitsu.app/anime/poster_images/1003/original.jpg",
  "movie-5": "https://media.kitsu.app/anime/poster_images/1004/original.jpg",
  "movie-6": "https://media.kitsu.app/anime/poster_images/1005/original.jpg",
  "movie-7": "https://media.kitsu.app/anime/poster_images/1006/original.jpg",
  "movie-8": "https://media.kitsu.app/anime/poster_images/1368/original.jpg",
  "movie-9": "https://media.kitsu.app/anime/poster_images/1992/original.jpg",
  "movie-10": "https://media.kitsu.app/anime/poster_images/2597/original.jpg",
  "movie-11": "https://media.kitsu.app/anime/poster_images/3419/original.jpg",
  "movie-12": "https://media.kitsu.app/anime/poster_images/4460/original.jpg",
  "movie-13": "https://media.kitsu.app/anime/poster_images/5083/original.jpg",
  "movie-14": "https://media.kitsu.app/anime/poster_images/6327/original.jpg",
  "movie-15": "https://media.kitsu.app/anime/poster_images/5939/original.jpg",
  "movie-16": "https://media.kitsu.app/anime/poster_images/6786/original.jpg",
  "movie-17": "https://media.kitsu.app/anime/poster_images/7489/original.jpg",
  "movie-18": "https://media.kitsu.app/anime/poster_images/8149/original.jpg",
  "movie-19": "https://media.kitsu.app/anime/poster_images/8903/original.png",
  "movie-20": "https://media.kitsu.app/anime/poster_images/11202/large.jpg",
  "movie-21": "https://media.kitsu.app/anime/poster_images/12941/original.jpg",
  "movie-22": "https://media.kitsu.app/anime/poster_images/41413/original.jpg",
  "movie-23": "https://media.kitsu.app/anime/41871/poster_image/3eadcf949282d8782ed3a60922f91760.png",
  "movie-24": "https://media.kitsu.app/anime/poster_images/43025/original.jpg",
};
